### ISSUE TITLE
Attempting to load data throws errors

### ISSUE THREAD

**Issue by boris377** [srclosson/div-panel#39]
When attempting a basic panel using the built in grafana queries, chrome starts throwing a bunch of errors. Having issues with any queries or libraries.

Using random walk, 2 errors are thrown as shown in the attached pictures.

[Pictures](https://imgur.com/a/MosWDMA)

Below is JSON

`{
  "__inputs": [],
  "__elements": {},
  "__requires": [
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "10.0.3"
    },
    {
      "type": "panel",
      "id": "grafana-div-panel",
      "name": "Div Panel",
      "version": "1.0.0"
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": null,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 1,
      "options": {
        "editor": {
          "content": "<html>\n<body>\n  <div>\n      Hello Div Panel\n  </div>\n\n  <script>\n      /**\n       * @param elem The div element containing your div panel\n       */\n      function onDivPanelInit(elem) {\n        console.log(\"I am in init\", elem);\n      }\n\n      /**\n       * @param data The data retrieved from your panel data config\n       */\n      function onDivPanelDataUpdate(data) {\n        console.log(\"I have data\", data);\n      }\n      \n      console.log(\"Hello from my script!\");\n  </script>\n</body>\n</html>",
          "editContent": [],
          "editCss": []
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "grafana"
          },
          "queryType": "randomWalk",
          "refId": "A"
        }
      ],
      "title": "Panel Title",
      "type": "grafana-div-panel"
    }
  ],
  "refresh": "",
  "schemaVersion": 38,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Div Panel Data Test",
  "uid": "aacaf7f9-cfdf-40b1-a490-372d48d58ccb",
  "version": 5,
  "weekStart": ""
}`

**Comment by srclosson** [comment]
@boris377 are you using grafana 10?

**Comment by boris377** [comment]
Yes you bet. Grafana 10.0.3 with a standard setup and a few exceptions for unsigned plugins.

When I attempt to build a new panel I get the following error:
importPanelPlugin.ts:55 Error loading panel plugin: grafana-div-panel Error: missing export: plugin or PanelCtrl
    at importPanelPlugin.ts:46:13
    at async actions.ts:142:16
    at async actions.ts:25:18

**Comment by srclosson** [comment]
@boris377 Would you try version 1.2.2 please? I think I got everything fixed.
