### ISSUE TITLE
Information concerning similar plugins

### ISSUE THREAD

**Issue by xkilian** [srclosson/div-panel#4]
Can you describe in the Readme how this plugin differs from the other Grafana plugins that permit html/javascript:
text panel
html panel
ajax plugin

ps. Love what you are doing with the OPC-UA plugin. Every automation person is waiting for a solid OPC Grafana plugin wheter they know it or not! ;-)

**Comment by srclosson** [comment]
@xkilian, For sure. I can update it with some extra info. I think the idea was to have this plugin be easier to use, with appropriate hooks. You should just be able to copy and paste from an example, and expect that it should work in the div panel. If the documentation for a 3rd party api says you should do things a certain way, you should be able to do it exactly the way documented.

Thanks for the OPC/UA feedback!  :)

**Comment by xkilian** [comment]
Thank you and have a great Grafanacon online. :-)
